// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: raftpb/chainconfig.proto

package raftpb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// 链角色（核心枚举）
type ChainRole int32

const (
	ChainRole_UNSPECIFIED ChainRole = 0
	ChainRole_HEAD        ChainRole = 1
	ChainRole_RELAY       ChainRole = 2
	ChainRole_TAIL        ChainRole = 3
)

var ChainRole_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "HEAD",
	2: "RELAY",
	3: "TAIL",
}

var ChainRole_value = map[string]int32{
	"UNSPECIFIED": 0,
	"HEAD":        1,
	"RELAY":       2,
	"TAIL":        3,
}

func (x ChainRole) String() string {
	return proto.EnumName(ChainRole_name, int32(x))
}

func (ChainRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1dc95f5473ed323d, []int{0}
}

// 链式复制配置参数（分片级）
type ChainConfig struct {
	EnableChain bool `protobuf:"varint,1,opt,name=enable_chain,json=enableChain,proto3" json:"enable_chain,omitempty"`
	// 静态拓扑配置（对应 READAAA.md 中“初始配置默认给出”的分片连接关系）
	PrevShardId     uint64   `protobuf:"varint,2,opt,name=prev_shard_id,json=prevShardId,proto3" json:"prev_shard_id,omitempty"`
	NextShardId     uint64   `protobuf:"varint,3,opt,name=next_shard_id,json=nextShardId,proto3" json:"next_shard_id,omitempty"`
	AvailableShards []uint64 `protobuf:"varint,4,rep,packed,name=available_shards,json=availableShards,proto3" json:"available_shards,omitempty"`
	// 策略参数（运行时不可修改，仅初始化时配置）
	SyncIntervalMs       uint64    `protobuf:"varint,5,opt,name=sync_interval_ms,json=syncIntervalMs,proto3" json:"sync_interval_ms,omitempty"`
	MaxRetryCount        uint64    `protobuf:"varint,6,opt,name=max_retry_count,json=maxRetryCount,proto3" json:"max_retry_count,omitempty"`
	ChainRole            ChainRole `protobuf:"varint,7,opt,name=chain_role,json=chainRole,proto3,enum=raftpb.ChainRole" json:"chain_role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ChainConfig) Reset()         { *m = ChainConfig{} }
func (m *ChainConfig) String() string { return proto.CompactTextString(m) }
func (*ChainConfig) ProtoMessage()    {}
func (*ChainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dc95f5473ed323d, []int{0}
}
func (m *ChainConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainConfig.Unmarshal(m, b)
}
func (m *ChainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainConfig.Marshal(b, m, deterministic)
}
func (m *ChainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainConfig.Merge(m, src)
}
func (m *ChainConfig) XXX_Size() int {
	return xxx_messageInfo_ChainConfig.Size(m)
}
func (m *ChainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ChainConfig proto.InternalMessageInfo

func (m *ChainConfig) GetEnableChain() bool {
	if m != nil {
		return m.EnableChain
	}
	return false
}

func (m *ChainConfig) GetPrevShardId() uint64 {
	if m != nil {
		return m.PrevShardId
	}
	return 0
}

func (m *ChainConfig) GetNextShardId() uint64 {
	if m != nil {
		return m.NextShardId
	}
	return 0
}

func (m *ChainConfig) GetAvailableShards() []uint64 {
	if m != nil {
		return m.AvailableShards
	}
	return nil
}

func (m *ChainConfig) GetSyncIntervalMs() uint64 {
	if m != nil {
		return m.SyncIntervalMs
	}
	return 0
}

func (m *ChainConfig) GetMaxRetryCount() uint64 {
	if m != nil {
		return m.MaxRetryCount
	}
	return 0
}

func (m *ChainConfig) GetChainRole() ChainRole {
	if m != nil {
		return m.ChainRole
	}
	return ChainRole_UNSPECIFIED
}

// GlobalChainConfig 链式复制全局配置（新增，跨分片共性规则）
type GlobalChainConfig struct {
	MaxChainLength          uint32   `protobuf:"varint,1,opt,name=max_chain_length,json=maxChainLength,proto3" json:"max_chain_length,omitempty"`
	DynamicAdjustIntervalMs uint64   `protobuf:"varint,2,opt,name=dynamic_adjust_interval_ms,json=dynamicAdjustIntervalMs,proto3" json:"dynamic_adjust_interval_ms,omitempty"`
	ServiceDiscoveryAddr    string   `protobuf:"bytes,3,opt,name=service_discovery_addr,json=serviceDiscoveryAddr,proto3" json:"service_discovery_addr,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *GlobalChainConfig) Reset()         { *m = GlobalChainConfig{} }
func (m *GlobalChainConfig) String() string { return proto.CompactTextString(m) }
func (*GlobalChainConfig) ProtoMessage()    {}
func (*GlobalChainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dc95f5473ed323d, []int{1}
}
func (m *GlobalChainConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalChainConfig.Unmarshal(m, b)
}
func (m *GlobalChainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalChainConfig.Marshal(b, m, deterministic)
}
func (m *GlobalChainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalChainConfig.Merge(m, src)
}
func (m *GlobalChainConfig) XXX_Size() int {
	return xxx_messageInfo_GlobalChainConfig.Size(m)
}
func (m *GlobalChainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalChainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalChainConfig proto.InternalMessageInfo

func (m *GlobalChainConfig) GetMaxChainLength() uint32 {
	if m != nil {
		return m.MaxChainLength
	}
	return 0
}

func (m *GlobalChainConfig) GetDynamicAdjustIntervalMs() uint64 {
	if m != nil {
		return m.DynamicAdjustIntervalMs
	}
	return 0
}

func (m *GlobalChainConfig) GetServiceDiscoveryAddr() string {
	if m != nil {
		return m.ServiceDiscoveryAddr
	}
	return ""
}

func init() {
	proto.RegisterEnum("raftpb.ChainRole", ChainRole_name, ChainRole_value)
	proto.RegisterType((*ChainConfig)(nil), "raftpb.ChainConfig")
	proto.RegisterType((*GlobalChainConfig)(nil), "raftpb.GlobalChainConfig")
}

func init() { proto.RegisterFile("raftpb/chainconfig.proto", fileDescriptor_1dc95f5473ed323d) }

var fileDescriptor_1dc95f5473ed323d = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x41, 0x8f, 0x12, 0x31,
	0x18, 0x86, 0x1d, 0x60, 0x71, 0xf9, 0x10, 0x98, 0x6d, 0x8c, 0x4e, 0x3c, 0x21, 0x07, 0x33, 0x7a,
	0x40, 0xa3, 0xde, 0xf6, 0x34, 0x01, 0xd4, 0x49, 0xd0, 0x98, 0xae, 0x1e, 0x3c, 0x35, 0x65, 0xda,
	0x5d, 0x6a, 0x3a, 0x2d, 0x69, 0xbb, 0x13, 0xf8, 0x45, 0x5e, 0xfd, 0x89, 0xa6, 0xdf, 0xc0, 0xba,
	0x7b, 0x9b, 0x3c, 0xef, 0x33, 0x6d, 0xde, 0x37, 0x85, 0xcc, 0xf1, 0xeb, 0xb0, 0xdb, 0xbc, 0xad,
	0xb6, 0x5c, 0x99, 0xca, 0x9a, 0x6b, 0x75, 0x33, 0xdf, 0x39, 0x1b, 0x2c, 0xe9, 0xb7, 0xc9, 0xec,
	0x4f, 0x07, 0x86, 0x8b, 0x98, 0x2e, 0x30, 0x25, 0x2f, 0xe1, 0x89, 0x34, 0x7c, 0xa3, 0x25, 0xc3,
	0x7f, 0xb2, 0x64, 0x9a, 0xe4, 0xe7, 0x74, 0xd8, 0x32, 0x14, 0xc9, 0x0c, 0x46, 0x3b, 0x27, 0x1b,
	0xe6, 0xb7, 0xdc, 0x09, 0xa6, 0x44, 0xd6, 0x99, 0x26, 0x79, 0x8f, 0x0e, 0x23, 0xbc, 0x8a, 0xac,
	0x14, 0xd1, 0x31, 0x72, 0x1f, 0xfe, 0x3b, 0xdd, 0xd6, 0x89, 0xf0, 0xe4, 0xbc, 0x86, 0x94, 0x37,
	0x5c, 0x69, 0xbc, 0x0d, 0x45, 0x9f, 0xf5, 0xa6, 0xdd, 0xbc, 0x47, 0x27, 0x77, 0x1c, 0x5d, 0x4f,
	0x72, 0x48, 0xfd, 0xc1, 0x54, 0x4c, 0x99, 0x20, 0x5d, 0xc3, 0x35, 0xab, 0x7d, 0x76, 0x86, 0x27,
	0x8e, 0x23, 0x2f, 0x8f, 0xf8, 0xab, 0x27, 0xaf, 0x60, 0x52, 0xf3, 0x3d, 0x73, 0x32, 0xb8, 0x03,
	0xab, 0xec, 0xad, 0x09, 0x59, 0x1f, 0xc5, 0x51, 0xcd, 0xf7, 0x34, 0xd2, 0x45, 0x84, 0xe4, 0x1d,
	0x00, 0x16, 0x64, 0xce, 0x6a, 0x99, 0x3d, 0x9e, 0x26, 0xf9, 0xf8, 0xfd, 0xc5, 0xbc, 0x1d, 0x65,
	0x8e, 0x3d, 0xa9, 0xd5, 0x92, 0x0e, 0xaa, 0xd3, 0xe7, 0xec, 0x6f, 0x02, 0x17, 0x9f, 0xb5, 0xdd,
	0x70, 0x7d, 0x7f, 0xaf, 0x1c, 0xd2, 0x78, 0x5f, 0x7b, 0x96, 0x96, 0xe6, 0x26, 0x6c, 0x71, 0xb3,
	0x11, 0x1d, 0xd7, 0x7c, 0x8f, 0xe6, 0x1a, 0x29, 0xb9, 0x84, 0x17, 0xe2, 0x60, 0x78, 0xad, 0x2a,
	0xc6, 0xc5, 0xef, 0x5b, 0x1f, 0x1e, 0xb4, 0x69, 0x37, 0x7c, 0x7e, 0x34, 0x0a, 0x14, 0xee, 0xd5,
	0xfa, 0x08, 0xcf, 0xbc, 0x74, 0x8d, 0xaa, 0x24, 0x13, 0xca, 0x57, 0xb6, 0x91, 0xee, 0xc0, 0xb8,
	0x10, 0x0e, 0x87, 0x1d, 0xd0, 0xa7, 0xc7, 0x74, 0x79, 0x0a, 0x0b, 0x21, 0xdc, 0x9b, 0x4b, 0x18,
	0xdc, 0x55, 0x21, 0x13, 0x18, 0xfe, 0xfc, 0x76, 0xf5, 0x7d, 0xb5, 0x28, 0x3f, 0x95, 0xab, 0x65,
	0xfa, 0x88, 0x9c, 0x43, 0xef, 0xcb, 0xaa, 0x58, 0xa6, 0x09, 0x19, 0xc0, 0x19, 0x5d, 0xad, 0x8b,
	0x5f, 0x69, 0x27, 0xc2, 0x1f, 0x45, 0xb9, 0x4e, 0xbb, 0x9b, 0x3e, 0x3e, 0x94, 0x0f, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x42, 0xec, 0xfb, 0x44, 0x44, 0x02, 0x00, 0x00,
}
