syntax = "proto3";
package raftpb;
// protoc --gogo_out=. raftpb/message1.proto

message Message {
    MessageType type = 1;
    uint64 to = 2;
    uint64 from = 3;
    uint64 shard_id = 4;
    uint64 term = 5;
    uint64 log_term = 6;
    uint64 log_index = 7;
    uint64 commit = 8;
    bool reject = 9;
    uint64 hint = 10;
    repeated Entry entries = 11;
    Snapshot snapshot = 12;
    uint64 hint_high = 13;
    
    // 新增字段
    uint64 next_shard = 18;
    ChainSyncRequest chain_sync = 19;
}
