// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: raft.proto

package raftpb

// Message 定义 Raft节点间通信的消息结构
type Message struct {
	Type     MessageType
	To       uint64
	From     uint64
	ShardID  uint64
	Term     uint64
	LogTerm  uint64
	LogIndex uint64
	Commit   uint64
	Reject   bool
	Hint     uint64
	Entries  []Entry
	Snapshot Snapshot
	HintHigh uint64
	// 新增：链式连接的下一跳 ShardID（用于递归构建链式拓扑）
	NextShard uint64 `protobuf:"varint,18,opt,name=next_shard,json=nextShard" json:"next_shard,omitempty"`
}

/*
关键说明
MarshalTo 方法

新增对 NextShard 字段的序列化逻辑，字段编号为 18（对应 protobuf 定义中的 next_shard = 18）。
使用 0x90（即 18 << 3 | proto.WireVarint）标识字段编号和类型，随后写入 NextShard 的 varint 值。
Size 方法

若 NextShard 非零，需累加其占用的字节数：1 字节（字段编号）+ sovRaft(uint64(m.NextShard))（varint 编码长度）。
兼容性

仅当 NextShard != 0 时才序列化该字段，避免空值占用额外空间，符合 protobuf 的 optional 语义。
为什么需要修改？
字段完整性：确保 NextShard 在节点间通信时被正确传输，否则链式连接的下一跳信息会丢失。
协议一致性：若不更新序列化/大小计算逻辑，新增字段会被忽略或导致数据 corruption，引发链式连接建立失败。
*/

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

// MarshalTo 将 Message 序列化到字节流（包含 NextShard 字段）
func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintRaft(dAtA, i, uint64(m.Type))
	dAtA[i] = 0x10
	i++
	i = encodeVarintRaft(dAtA, i, uint64(m.To))
	dAtA[i] = 0x18
	i++
	i = encodeVarintRaft(dAtA, i, uint64(m.From))
	dAtA[i] = 0x20
	i++
	i = encodeVarintRaft(dAtA, i, uint64(m.ShardID))
	dAtA[i] = 0x28
	i++
	i = encodeVarintRaft(dAtA, i, uint64(m.Term))
	dAtA[i] = 0x30
	i++
	i = encodeVarintRaft(dAtA, i, uint64(m.LogTerm))
	dAtA[i] = 0x38
	i++
	i = encodeVarintRaft(dAtA, i, uint64(m.LogIndex))
	dAtA[i] = 0x40
	i++
	i = encodeVarintRaft(dAtA, i, uint64(m.Commit))
	dAtA[i] = 0x48
	i++
	if m.Reject {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x50
	i++
	i = encodeVarintRaft(dAtA, i, uint64(m.Hint))
	if len(m.Entries) > 0 {
		for _, msg := range m.Entries {
			dAtA[i] = 0x5a
			i++
			i = encodeVarintRaft(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x62
	i++
	i = encodeVarintRaft(dAtA, i, uint64(m.Snapshot.Size()))
	n2, err := m.Snapshot.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	dAtA[i] = 0x68
	i++
	i = encodeVarintRaft(dAtA, i, uint64(m.HintHigh))

	// 新增：序列化 NextShard 字段（字段编号 18）
	if m.NextShard != 0 {
		dAtA[i] = 0x90 // 字段编号 18 的 varint 编码（18 << 3 | WireVarint = 144 = 0x90）
		i++
		i = encodeVarintRaft(dAtA, i, m.NextShard)
	}
	return i, nil
}

func (m *Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovRaft(uint64(m.Type))
	n += 1 + sovRaft(uint64(m.To))
	n += 1 + sovRaft(uint64(m.From))
	n += 1 + sovRaft(uint64(m.ShardID))
	n += 1 + sovRaft(uint64(m.Term))
	n += 1 + sovRaft(uint64(m.LogTerm))
	n += 1 + sovRaft(uint64(m.LogIndex))
	n += 1 + sovRaft(uint64(m.Commit))
	n += 2
	n += 1 + sovRaft(uint64(m.Hint))
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovRaft(uint64(l))
		}
	}
	l = m.Snapshot.Size()
	n += 1 + l + sovRaft(uint64(l))
	n += 1 + sovRaft(uint64(m.HintHigh))

	// 新增：NextShard 字段的大小（varint 类型）
	if m.NextShard != 0 {
		n += 1 + sovRaft(uint64(m.NextShard)) // 1 字节字段编号 + varint 大小
	}

	return n
}
