// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: raft.proto

package raftpb

type MessageType int32

const (
	LocalTick          MessageType = 0
	Election           MessageType = 1
	LeaderHeartbeat    MessageType = 2
	ConfigChangeEvent  MessageType = 3
	NoOP               MessageType = 4
	Ping               MessageType = 5
	Pong               MessageType = 6
	Propose            MessageType = 7
	SnapshotStatus     MessageType = 8
	Unreachable        MessageType = 9
	CheckQuorum        MessageType = 10
	BatchedReadIndex   MessageType = 11
	Replicate          MessageType = 12
	ReplicateResp      MessageType = 13
	RequestVote        MessageType = 14
	RequestVoteResp    MessageType = 15
	InstallSnapshot    MessageType = 16
	Heartbeat          MessageType = 17
	HeartbeatResp      MessageType = 18
	ReadIndex          MessageType = 19
	ReadIndexResp      MessageType = 20
	Quiesce            MessageType = 21
	SnapshotReceived   MessageType = 22
	LeaderTransfer     MessageType = 23
	TimeoutNow         MessageType = 24
	RateLimit          MessageType = 25
	RequestPreVote     MessageType = 26
	RequestPreVoteResp MessageType = 27
	LogQuery           MessageType = 28
	// 新增：领导者链式连接消息类型
	LeaderChainConnect    MessageType = 29 // 链式连接请求（上游→下游）
	LeaderChainAck        MessageType = 30 // 链式连接确认（下游→上游）
	LeaderChainPing       MessageType = 31 // 链式连接健康检查（双向）
	LeaderChainDisconnect MessageType = 32 // 新增：链式连接断开（双向）
	LeaderChainPong       MessageType = 33 // 新增：链式连接 Pong 消息（上游→下游）
)

/*
pb.LeaderChainPong 的作用
pb.LeaderChainPong 是 链式连接健康检查的响应消息，用于确认下游 Raft 组领导者已收到上游发送的健康检查请求（LeaderChainPing）。其核心作用包括：

1. 连接活性验证
上游领导者定期发送 LeaderChainPing 消息（如每 30 秒），下游领导者收到后必须返回 LeaderChainPong 响应。
上游通过记录 chainDownstream.lastPingAck 时间戳，判断下游连接是否存活（超时未收到 Pong 则触发重连）。
2. 超时重连触发
在 leaderChainHealthTick 定时任务中，通过检查 lastPingAck 是否超时（如 30 秒），决定是否重新发起下游连接：
3. 双向健康检查闭环
LeaderChainPing（请求）和 LeaderChainPong（响应）形成完整的健康检查机制，确保链式连接的双向可达性，避免“单边连接”（仅上游能连下游，下游无法响应）导致的数据同步异常。
*/

// 更新消息类型名称映射（用于日志和调试）
var MessageType_name = map[int32]string{
	0:  "LocalTick",
	1:  "Election",
	2:  "LeaderHeartbeat",
	3:  "ConfigChangeEvent",
	4:  "NoOP",
	5:  "Ping",
	6:  "Pong",
	7:  "Propose",
	8:  "SnapshotStatus",
	9:  "Unreachable",
	10: "CheckQuorum",
	11: "BatchedReadIndex",
	12: "Replicate",
	13: "ReplicateResp",
	14: "RequestVote",
	15: "RequestVoteResp",
	16: "InstallSnapshot",
	17: "Heartbeat",
	18: "HeartbeatResp",
	19: "ReadIndex",
	20: "ReadIndexResp",
	21: "Quiesce",
	22: "SnapshotReceived",
	23: "LeaderTransfer",
	24: "TimeoutNow",
	25: "RateLimit",
	26: "RequestPreVote",
	27: "RequestPreVoteResp",
	28: "LogQuery",
	// 新增
	29: "LeaderChainConnect",
	30: "LeaderChainAck",
	31: "LeaderChainPing",
	32: "LeaderChainDisconnect", // 新增：断开连接类型映射
	33: "LeaderChainPong",       // 新增：Pong消息类型映射
}

var MessageType_value = map[string]int32{
	"LocalTick":          0,
	"Election":           1,
	"LeaderHeartbeat":    2,
	"ConfigChangeEvent":  3,
	"NoOP":               4,
	"Ping":               5,
	"Pong":               6,
	"Propose":            7,
	"SnapshotStatus":     8,
	"Unreachable":        9,
	"CheckQuorum":        10,
	"BatchedReadIndex":   11,
	"Replicate":          12,
	"ReplicateResp":      13,
	"RequestVote":        14,
	"RequestVoteResp":    15,
	"InstallSnapshot":    16,
	"Heartbeat":          17,
	"HeartbeatResp":      18,
	"ReadIndex":          19,
	"ReadIndexResp":      20,
	"Quiesce":            21,
	"SnapshotReceived":   22,
	"LeaderTransfer":     23,
	"TimeoutNow":         24,
	"RateLimit":          25,
	"RequestPreVote":     26,
	"RequestPreVoteResp": 27,
	"LogQuery":           28,
	// 新增
	"LeaderChainConnect":    29,
	"LeaderChainAck":        30,
	"LeaderChainPing":       31,
	"LeaderChainDisconnect": 32, // 新增：断开连接类型反向映射
	"LeaderChainPong":       33, // 新增：Pong消息类型反向映射
}

func (x MessageType) String() string {
	return MessageType_name[int32(x)]
}

type EntryType int32

const (
	ApplicationEntry  EntryType = 0
	ConfigChangeEntry EntryType = 1
	EncodedEntry      EntryType = 2
	MetadataEntry     EntryType = 3
)

var EntryType_name = map[int32]string{
	0: "ApplicationEntry",
	1: "ConfigChangeEntry",
	2: "EncodedEntry",
	3: "MetadataEntry",
}

var EntryType_value = map[string]int32{
	"ApplicationEntry":  0,
	"ConfigChangeEntry": 1,
	"EncodedEntry":      2,
	"MetadataEntry":     3,
}

func (x EntryType) String() string {
	return EntryType_name[int32(x)]
}

type ConfigChangeType int32

const (
	AddNode      ConfigChangeType = 0
	RemoveNode   ConfigChangeType = 1
	AddNonVoting ConfigChangeType = 2
	AddWitness   ConfigChangeType = 3
)

var ConfigChangeType_name = map[int32]string{
	0: "AddNode",
	1: "RemoveNode",
	2: "AddNonVoting",
	3: "AddWitness",
}

var ConfigChangeType_value = map[string]int32{
	"AddNode":      0,
	"RemoveNode":   1,
	"AddNonVoting": 2,
	"AddWitness":   3,
}

func (x ConfigChangeType) String() string {
	return ConfigChangeType_name[int32(x)]
}

type StateMachineType int32

const (
	UnknownStateMachine    StateMachineType = 0
	RegularStateMachine    StateMachineType = 1
	ConcurrentStateMachine StateMachineType = 2
	OnDiskStateMachine     StateMachineType = 3
)

var StateMachineType_name = map[int32]string{
	0: "UnknownStateMachine",
	1: "RegularStateMachine",
	2: "ConcurrentStateMachine",
	3: "OnDiskStateMachine",
}

var StateMachineType_value = map[string]int32{
	"UnknownStateMachine":    0,
	"RegularStateMachine":    1,
	"ConcurrentStateMachine": 2,
	"OnDiskStateMachine":     3,
}

func (x StateMachineType) String() string {
	return StateMachineType_name[int32(x)]
}

type CompressionType int32

const (
	NoCompression CompressionType = 0
	Snappy        CompressionType = 1
)

var CompressionType_name = map[int32]string{
	0: "NoCompression",
	1: "Snappy",
}

var CompressionType_value = map[string]int32{
	"NoCompression": 0,
	"Snappy":        1,
}

func (x CompressionType) String() string {
	return CompressionType_name[int32(x)]
}

type ChecksumType int32

const (
	CRC32IEEE ChecksumType = 0
	HIGHWAY   ChecksumType = 1
)

var ChecksumType_name = map[int32]string{
	0: "CRC32IEEE",
	1: "HIGHWAY",
}

var ChecksumType_value = map[string]int32{
	"CRC32IEEE": 0,
	"HIGHWAY":   1,
}

func (x ChecksumType) String() string {
	return ChecksumType_name[int32(x)]
}
